### ISSUE TITLE
Is there an api with that app?

### ISSUE THREAD

**Issue by voyantt** [bryanbrunetti/barbados#1]
Is there an api with that app? (ex. *site*.herokuapp.com/url-shorten?longurl=http://synkmc.net)

**Comment by bryanbrunetti** [comment]
No, there isn't an API like that.
The [url() method](https://github.com/bryanbrunetti/barbados/blob/master/app.py#L136) is where the URL redirect resources are created, and it requires an authenticated session and POST data.

Feel free to fork the repo and add in this functionality!
